export enum StaffRoles {
	SUPER_ADMIN = 'SUPER_ADMIN',
	SELLER = 'SELLER',
	COURIER = 'COURIER',
	ACCOUNTANT = 'ACCOUNTANT',
	PRODUCER = 'PRODUCER',
	STOREKEEPER = 'STOREKEEPER',
	MAIN_STOREKEEPER = 'MAIN_STOREKEEPER',
}
